algoritmo "ConteAté10"
// Função :
// Autor :
// Data : 8/22/2024
// Seção de Declarações
var
valor, salto, contador:inteiro

inicio
// Seção de Comandos
contador <- 0
escreva ("Quer contar até quanto? ")
leia(valor)
escreva ("De quanto em quanto? ")
leia(salto)
enquanto (contador <= valor) faca
   escreval (contador)
   contador <- contador + salto
fimenquanto
escreval ("Terminei de contar!")
fimalgoritmo
